### ISSUE TITLE
bfs uses fcntl while find doesn't (unnecessary F_SETFD FD_CLOEXEC)

### ISSUE THREAD

**Issue by aktau** [tavianator/bfs#9] opened 2016-03-23 10:14 UTC
Running the following:

```bash
strace -c bfs -links 2 >/dev/null ; strace -c find . -links 2 >/dev/null 
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 63.99    0.000972           2       530           newfstatat
 10.40    0.000158           0       374           getdents
  5.46    0.000083           0       558           fcntl
  4.41    0.000067           0       187           openat
  3.09    0.000047           0       375           close
  2.83    0.000043           5         9           mmap
  2.70    0.000041           0       189           fstat
  1.51    0.000023           6         4           mprotect
  1.18    0.000018           6         3         3 access
  0.86    0.000013           7         2           open
  0.79    0.000012          12         1           execve
  0.72    0.000011           4         3           brk
  0.72    0.000011           4         3         2 ioctl
  0.66    0.000010           5         2           munmap
  0.26    0.000004           4         1           read
  0.20    0.000003           3         1           getrlimit
  0.20    0.000003           3         1           arch_prctl
  0.00    0.000000           0         1           write
------ ----------- ----------- --------- --------- ----------------
100.00    0.001519                  2244         5 total
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 23.69    0.002030           4       530           newfstatat
 18.37    0.001574           4       372           getdents
 15.33    0.001314           3       379           close
 13.06    0.001119           3       375           fchdir
 10.65    0.000913           5       186           openat
 10.26    0.000879           4       196         4 open
  6.60    0.000566           3       191           fstat
  0.68    0.000058           5        12           mmap
  0.40    0.000034           6         6           mprotect
  0.21    0.000018           5         4         4 access
  0.18    0.000015           4         4           read
  0.16    0.000014           5         3           munmap
  0.13    0.000011           4         3           brk
  0.12    0.000010           3         3         2 ioctl
  0.11    0.000009           9         1           execve
  0.04    0.000003           3         1           uname
  0.04    0.000003           3         1           arch_prctl
  0.00    0.000000           0         1           write
------ ----------- ----------- --------- --------- ----------------
100.00    0.008570                  2268        10 total
```

I suspect the reason to be that `find` passed `O_CLOEXEC` to `openat(2)`, while `bfs` does it in a separate `fcntl(2)` call or something. Which is valid because it doesn't `fork` but could be avoided.

Let's check.

```bash
$ strace find . -links 2 >/dev/null |& grep 'CLOEXEC' | tail
openat(AT_FDCWD, "d7", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 5
openat(AT_FDCWD, "27", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 5
openat(AT_FDCWD, "logs", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 5
openat(AT_FDCWD, "refs", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 5
openat(AT_FDCWD, "remotes", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 5
openat(AT_FDCWD, "origin", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 5
openat(AT_FDCWD, "heads", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 5
openat(AT_FDCWD, "hooks", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 5
openat(AT_FDCWD, "branches", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 5
openat(AT_FDCWD, "info", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 5
openat(AT_FDCWD, ".git", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 5
```

`bfs` does a strange sort of dance:

```bash
$  strace bfs -links 2 >/dev/null |& grep -P 'close|open|CLOEXEC' | less
...
openat(6, "73/", O_RDONLY|O_DIRECTORY|O_CLOEXEC) = 9
fcntl(9, F_DUPFD_CLOEXEC, 0)            = 10
fcntl(10, F_SETFD, FD_CLOEXEC)          = 0
close(10)                               = 0
close(9)                                = 0
...
```

If I'm seeing that right, there's no reason to to the `fcntl(10, F_SETFD, FD_CLOEXEC)` operation after `fcntl(9, F_DUPFD_CLOEXEC, 0) ` is called, From http://man7.org/linux/man-pages/man2/fcntl.2.html:

> F_DUPFD_CLOEXEC (int; since Linux 2.6.24)
>        As for F_DUPFD, but additionally set the close-on-exec flag
>        for the duplicate file descriptor.  Specifying this flag
>        permits a program to avoid an additional fcntl() F_SETFD
>        operation to set the FD_CLOEXEC flag.  For an explanation of
>        why this flag is useful, see the description of O_CLOEXEC in
>        open(2).

As for the `dup` call which `find` doesn't do, I think it might have something to do with the breadth-first ways of `bfs`. So that could be required for proper functioning. Don't know.

**Comment by aktau** [comment] 2016-03-23 10:16
As a sidenote, I'm really wondering why the `newfstatat(2)` calls are so much faster for bfs than they are for find. Perhaps doing breadt-first searching is better for the kernel? Cache line behaviour? In fact it should probably all fit in cache, I ran this on the .git repository.

**Comment by tavianator** [comment] 2016-03-23 19:33
So the weird `dup` dance I can explain: `bfs` wants to keep lots of open fds around to use for `openat()` calls in the future.  Unfortunately, keeping the entire `DIR*` around takes a lot of memory, so it does this instead:

```c
int cachedfd = openat(at_fd, at_path, O_RDONLY | O_DIRECTORY | O_CLOEXEC);
int fd = fcntl(entry->fd, F_DUPFD_CLOEXEC, 0);
DIR *dir = fdopendir(fd);
struct dirent *de;
while ((de = readdir(dir)) != NULL) {
  // Do stuff
}
closedir(dir);
// Now dir and fd are closed, but cachedfd remains open
```

So that explains the strange dance of `openat` followed by `F_DUPFD_CLOEXEC`.  Sadly `glibc` itself does this inside of `fdopendir()`:

```
fstat(4, {st_mode=S_IFDIR|0755, st_size=88, ...}) = 0
fcntl(4, F_GETFL)                       = 0x18000 (flags O_RDONLY|O_LARGEFILE|O_DIRECTORY)
fcntl(4, F_SETFD, FD_CLOEXEC)           = 0
```

`F_GETFL` is to check that the fd is readable.  `F_SETFD, FD_CLOEXEC` is to force the `DIR*` to close on exec (a requirement of POSIX).  The worst one is the `fstat()` which is done to make sure the fd is a directory, and to get the recommended block size (`st_blksize`).  Unfortunately it means there's at least one `fstat()` per directory that `bfs` can't do anything about.

`glibc` could do the `F_GETFL` first, and avoid the `fstat()` if it sees `O_DIRECTORY`.  It wouldn't have `st_blksize` then, but I'm sure `4096` or something is a reasonable default.  I plan to submit such a patch to `glibc` when I get around to it.  `F_SETFD, FD_CLOEXEC` may be avoided by doing `F_GETFD` first, but I'm not sure that's a win.

Ideally we'd do something like this:

```c
DIR *dir = opendirat(at_fd, at_path);
int cachedfd = dirfd(dir);
struct dirent *de;
while ((de = readdir(dir)) != NULL) {
  // Do stuff
}
freedir(dir); // But don't close the fd yet
```

but neither `opendirat()` nor `freedir()` exist.

RE: your sidenote, you're right that the `newfstatat()` calls in `bfs` are faster due to nicer cache locality caused by the breadth-first traversal.  For a given directory, `bfs` calls `newfstatat()` on all its children consecutively, so if the `stat` infos are close together it's a big win.

**Comment by tavianator** [comment] 2016-03-23 21:11
Interestingly I'm actually seeing `find` make *way* more `fcntl()` calls than `bfs`:

```
tavianator@cosmicray $ strace -c bfs -links 2
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 41.04    0.000385           0     68515           newfstatat
 23.13    0.000217           0     22667           getdents
 13.43    0.000126           0     33996           fcntl
 11.19    0.000105           0     22667           close
  6.61    0.000062           0     11332           openat
  4.58    0.000043           0     11335           fstat
...
------ ----------- ----------- --------- --------- ----------------
100.00    0.000938                170543         1 total
tavianator@cosmicray $ strace -c find -links 2
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 31.41    0.000462           0     79847           newfstatat
 30.46    0.000448           0    102183           fcntl
 22.23    0.000327           0     22665           getdents
 11.42    0.000168           0     45170           close
  2.99    0.000044           0     11696           fstat
  1.50    0.000022           0     11691           openat
...
------ ----------- ----------- --------- --------- ----------------
100.00    0.001471                273323         7 total
```

I suspect this may have changed in findutils 4.6.0 which I'm now running.

**Comment by tavianator** [comment] 2016-03-23 21:23
Wow yeah, `find` has regressed badly in this regard:

```
$ strace find -links 2
...
newfstatat(7, "branches", {st_mode=S_IFDIR|0755, st_size=0, ...}, AT_SYMLINK_NOFOLLOW) = 0
close(4)                                = 0
fcntl(7, F_DUPFD_CLOEXEC, 0)            = 4
openat(7, "branches", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_DIRECTORY|O_NOFOLLOW) = 6
fcntl(6, F_GETFD)                       = 0
fcntl(6, F_SETFD, FD_CLOEXEC)           = 0
fstat(6, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
fcntl(6, F_GETFL)                       = 0x38800 (flags O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_DIRECTORY|O_NOFOLLOW)
fcntl(6, F_SETFD, FD_CLOEXEC)           = 0
newfstatat(7, "branches", {st_mode=S_IFDIR|0755, st_size=0, ...}, AT_SYMLINK_NOFOLLOW) = 0
fcntl(6, F_DUPFD, 3)                    = 8
fcntl(8, F_GETFD)                       = 0
fcntl(8, F_SETFD, FD_CLOEXEC)           = 0
getdents(6, /* 2 entries */, 32768)     = 48
getdents(6, /* 0 entries */, 32768)     = 0
close(6)                                = 0
close(8)                                = 0
close(4)                                = 0
fcntl(7, F_DUPFD_CLOEXEC, 0)            = 4
...
```

Notice that `fcntl(7, F_DUPFD_CLOEXEC, 0)            = 4` is done, but file descriptor 4 is never used, except to close it later.  So it looks like findutils 4.6.0 is doing a similar thing to `bfs`, but way worse.

**Comment by aktau** [comment] 2016-03-24 22:03
Thanks for the clear analysis, that indeed clears it up. I suppose then the way to truly optimize this is to go very platform-specific. The non-portability would likely make it a maintainers nightmare and a speed bump is not sure at all (though I'd be interested to try). You can close this, if you want :).

**Comment by tavianator** [comment] 2016-03-28 18:34
Yeah in order to avoid the glibc weirdness there I'd have to avoid using `DIR*` entirely AFAICS, which would be a portability/maintainability headache.  But thanks anyway for the report!

**Closed by tavianator** 2016-03-28 18:34 UTC
Labels: upstream

**Comment by tavianator** [comment] 2016-06-08 01:11
See https://savannah.gnu.org/bugs/index.php?48169 for the findutils 4.6 bug
